### ISSUE TITLE
Any considerations for correcting assemblies rather than reads?

### ISSUE THREAD

**Issue by flashton2003** [thackl/proovframe#3]
I'm interested in using proovframe to correct artefactual indels in de novo assemblies generated using e.g. flye from MinION R9.4.1 data.

The command line options you give in the readme are for correcting reads rather than assemblies.

Are there any particular considerations to take into account when using proovframe for ONT assemblies, rather than reads?

Thanks!

**Comment by thackl** [comment]
Hi,

Good question. You can use the same parameters. They work just as well for assemblies.

The only optimization you could aim for is speed - if that is an issue. Assuming a lot fewer indels than in raw reads, you could reduce the sensitivity for the diamond run and still get sufficient mappings. This is right now hard-coded in proovframe-map around line 51 (diamond mode --more-sensitive)

**Comment by flashton2003** [comment]
Great, thanks!

**Comment by thackl** [comment]
Just a follow-up, we just posted a preprint with a dedicated section on assembly correction (https://doi.org/10.1101/2021.08.23.457338 ).

**Comment by flashton2003** [comment]
Thanks!
