### ISSUE TITLE
bioconda

### ISSUE THREAD

**Issue by thanhleviet** [thackl/proovframe#4]
Hi,

This is a nice tool, would it be possible to make a release for it so we can pack it to bioconda ?

Thanks
Thanh

**Comment by thackl** [comment]
Absolutely! Just created one. Thanks for asking.

**Comment by ZarulHanifah** [comment]
Sorry, but I can't find the conda distribution in bioconda?

**Comment by jmeppley** [comment]
I don't think it ever got created. @thanhleviet?

**Comment by jmeppley** [comment]
@ZarulHanifah, I don't see a bioconda package yet either. I've started the process to get it into bioconda, but it may take a day or so. 

In the meantime, I threw a package up on my personal channel:

    $ conda install -c jmeppley proovframe

(NOTE: You still need the [bioconda and conda-forge channels configured](https://bioconda.github.io/user/install.html#set-up-channels) for dependencies. )

**Comment by ZarulHanifah** [comment]
You sir are really awesome. Thank you so much.

**Comment by thackl** [comment]
Thanks @jmeppley!!

**Comment by jmeppley** [comment]
Update:  @thanhleviet  has come through with the bioconda package.
