### ISSUE TITLE
Silencing diamond

### ISSUE THREAD

**Issue by MaozGelbart** [thackl/proovframe#5]
Hi, thanks for the nice tool!

I've noticed diamond outputs many lines, which are not useful for proovframe's end-user. Hence calling diamond with a `--quiet` flag may improve proovframe's output readability. 

Thanks again for the helpful tool.

**Comment by thackl** [comment]
You can add diamond flags after a `--` at the end of a map call: 
`proovframe map [-a|-d proteins] -o alignments.o6 seqs.fa -- extra-diamond-params`
so something like this should suppress diamond logs 
`proovframe map -a prot.faa aln.o6. seqs.fa -- --quiet`
