### ISSUE TITLE
Eukaryotic genome

### ISSUE THREAD

**Issue by bsb2014** [thackl/proovframe#8]
Can proofframe work with eukaryotic genome? Thanks.

**Comment by thackl** [comment]
With limitations... It will align proteins partially to exons and will remove frameshifts within exons. However, it might also misalign/overcorrect intron-exon boundaries. So I'd suggest to use it with care and ideally with eukaryotes with few introns (I've used in on some protists and fungi, ...)

**Comment by bsb2014** [comment]
Thanks for your suggestion.
